name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish_package1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Choose your preferred Python version
          
      - name: Build and Publish Package 1
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine
          python3 -m build
          echo $TWINE_USERNAME
          echo $TWINE_PASSWORD
          python3 -m twine upload dist/*